<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
  <Actions category="Scripts">
    <text>SwitchBrushAlternative</text>

    <Action name="sb_alternative_next">
      <icon></icon>
      <text>Switch Next Alternate</text>
      <whatsThis></whatsThis>
      <toolTip></toolTip>
      <activationFlags>10000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="sb_alternative_prev">
      <icon></icon>
      <text>Switch Previous Alternate Brush</text>
      <whatsThis></whatsThis>
      <toolTip></toolTip>
      <activationFlags>10000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>

  </Actions>
</ActionCollection>
